packages:
  - starters/*

ignoreWorkspaceRootCheck: true

patchedDependencies:
  '@nimiq/core@2.2.0': patches/@nimiq__core@2.2.0.patch

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - simple-git-hooks

shellEmulator: true
