packages:
  - starters/*

ignoreWorkspaceRootCheck: true

patchedDependencies:
  '@nimiq/core@2.1.1': patches/@nimiq__core@2.1.1.patch

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - simple-git-hooks

shellEmulator: true
