packages:
  - starters/*

ignoreWorkspaceRootCheck: true

# patchedDependencies:
#   '@nimiq/core': patches/@nimiq__core.patch

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - simple-git-hooks

shellEmulator: true
