packages:
  - docs
  - starters/*

catalog:
  '@nimiq/core': ^2.1.1
  '@tsconfig/node22': ^22.0.2
  '@types/jsdom': ^21.1.7
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/browser': ^3.2.4
  '@vitest/eslint-plugin': ^1.3.4
  '@vue/eslint-config-prettier': ^10.2.0
  '@vue/eslint-config-typescript': ^14.6.0
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  eslint-plugin-vue: ~10.3.0
  jiti: ^2.4.2
  jsdom: ^26.1.0
  npm-run-all2: ^8.0.4
  playwright: ^1.55.1
  prettier: 3.6.2
  vite-plugin-top-level-await: ^1.6.0
  vite-plugin-vue-devtools: ^8.0.0
  vite-plugin-wasm: ^3.5.0
  vitepress: ^1.3.4
  vue: ^3.5.18
  vue-tsc: ^3.0.4

catalogs:
  cli:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.0.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.15.4
    tsx: ^4.20.5
    typescript: ^5.9.2
    vite: ^7.1.7
  conflicts_cli_h7_0_6:
    vite: ^7.0.6
  conflicts_cli_h9_31_0:
    eslint: ^9.31.0
  conflicts_cli_t5_8_0:
    typescript: ~5.8.0
  conflicts_types_h22_16_5:
    '@types/node': ^22.16.5
  inlined:
    '@antfu/utils': ^9.2.1
  testing:
    tinyexec: ^1.0.1
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.5.2

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - simple-git-hooks

patchedDependencies:
  '@nimiq/core': patches/@nimiq__core.patch

shellEmulator: true
