name = "nimiq-starter-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-12-25"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "npm run build"

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[[rules]]
type = "CompiledWasm"
globs = [ "**/*.wasm" ]
