name: Cloudflare CI

on:
  push:
    branches:
      - main
    paths:
      - 'starters/cloudflare-d1/**'

  pull_request:
    branches:
      - main
    paths:
      - 'starters/cloudflare-d1/**'

  schedule:
    - cron: '0 0 1 * *' # Run monthly on the 1st at midnight UTC

jobs:
  cloudflare-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm i -g @antfu/ni
      - run: nci

      - run: pnpm --filter nimiq-cloudflare-d1 typecheck
      - run: pnpm --filter nimiq-cloudflare-d1 test
      - run: pnpm --filter nimiq-cloudflare-d1 build
