name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        starter: [vue-ts]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm i -g @antfu/ni
      - run: nci
      - run: cd starters/${{ matrix.starter }} && pnpm typecheck
      - run: cd starters/${{ matrix.starter }} && pnpm test
      - run: cd starters/${{ matrix.starter }} && pnpm build
