name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [nimiq-vue-ts]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm i -g @antfu/ni
      - run: nci
      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1
      - run: pnpm --filter ${{ matrix.package }} typecheck
      - run: pnpm --filter ${{ matrix.package }} test
      - run: pnpm --filter ${{ matrix.package }} build
