name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [nimiq-vue-ts, nimiq-react-ts, nimiq-nextjs, nimiq-cloudflare-d1]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm i -g @antfu/ni
      - run: nci

      - name: Install Playwright Browsers
        run: |
          if pnpm --filter ${{ matrix.package }} exec playwright --version >/dev/null 2>&1; then
            pnpm --filter ${{ matrix.package }} exec playwright install --with-deps chromium
          else
            echo "Playwright not found in ${{ matrix.package }}, skipping browser installation"
          fi

      - run: pnpm --filter ${{ matrix.package }} typecheck
      - run: pnpm --filter ${{ matrix.package }} test
      - run: pnpm --filter ${{ matrix.package }} build
